# Generated by Django 2.1.5 on 2019-01-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smwc_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('smwc_href', models.CharField(max_length=255)),
                ('file_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('demo', models.BooleanField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hacks',
                'verbose_name_plural': 'Hacks',
            },
        ),
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=255)),
                ('webhook_url', models.URLField(unique=True)),
                ('hook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('guild_id', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhooks',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
